site_name: Rukmi's VLSI Notes

theme:
  name: material

nav:
  - Home: index.md

  - Inputs:
      - Liberty File (.lib): inputs/lib.md

  - VIM: vim/vim.md
  - TCL: tcl/tcl.md
  - Python: python/python.md
  - Git: git/git.md 
  - Markdown: markdown/markdown.md
  - unix: 
    - Basic: unix/unix-basic.md
    - Advance: unix/unix-adv.md
    - AWK/GREP/SED: unix/awk-grep-sed.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format