site_name: Rukmi's VLSI Notes

theme:
  name: material

nav:
  - Home: index.md

  - Inputs:
      - Technology Files: inputs/tech.md

  - Physical Design:
      - Liberty File: physical-design/liberty-file.md